### ISSUE TITLE
PHP 7.1.3 in requirements

### ISSUE THREAD

**Issue by luza** [fre5h/transliteration-php#13]
Why so specific PHP version is required? Can the requirement be less tight, like >=7.1?
As I can see there is no syntax changes between 7.1.0 <> 7.1.3, so I guess it is a safe to change.

**Comment by fre5h** [comment]
@luza Hi, I looked at Symony 4, it requires at least 7.1.3, so I did same. I don't really know the reason for such minimal version, I suppose it is related to some critical bug, etc.
Do you use this library with PHP => 7.1.0 and < 7.1.3?

**Comment by fre5h** [comment]
I think Symfony uses >=7.1.3 because of this issue https://bugs.php.net/bug.php?id=73989
Anyway it does not affect transliteration library, so I will decrease the PHP version

**Comment by fre5h** [comment]
Take new release `v2.0.3`

**Comment by luza** [comment]
Thanks.
